### ISSUE TITLE
Changing biome colors?

### ISSUE THREAD

**Issue by Tonas1997** [fraenkelc/amidst-forge#16]
Not exactly an issue per se, but the biome color coding isn't very clear at times, especially with mods such as Biomes o' Plenty (which adds a lot of quasi-similar biomes). For instance, some forest biomes will be mapped to a strong aqua blue, or even bright pink.

Is there a way to explicitly define how biomes will look like in the Amidst viewport? Something like a .cfg file mapping colors to IDs?

**Comment by fraenkelc** [comment]
I agree, the current biome colors are a mess. To be honest I didn't invest any time in them at all and just generated them at random ;)
Amidst has a mechanism for changing Biome Profiles. Good news is I just tested it on the current 1.14 build and it turns out I didn't break it ;). To make it work you'll need to do the following:
* create a folder called "biome" inside your minecraft instance.
* start amidst from minecraft
* amidst should now create a file called "default.json" containing biome colors for standard minecraft biomes
* you can add modded biomes to this file using their displayed name in amidst.
* you can change the biome profile (you can have multiple files) and reload them using the menu item in Amidst
![image](https://user-images.githubusercontent.com/4005102/74064598-4c0ca880-49f3-11ea-857f-8a22f36f1551.png)

Here's an example of me changing the arid highlands to white:
![image](https://user-images.githubusercontent.com/4005102/74064729-93933480-49f3-11ea-9ff8-84730af2538e.png)

The changes persist through restarts as they are stored in a separate file but you might need to reselect the biome profile when you restart amidst.

**Comment by Tonas1997** [comment]
Thanks! Sadly I'm still on 1.12.2, but this is definitely a nice feature for the mod to have from now onwards!

**Comment by fraenkelc** [comment]
Just tested it, the Amidst feature works the same in 1.12.2, so you should be all set.
